apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/amin4m/order-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: SNS_TOPIC_ARN
          value: "arn:aws:sns:us-east-1:864981715490:order-events"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  ports:
port: 80
targetPort: 3000
  selector:
app: order-service