replicaCount: 2
image:
  repository: ghcr.io/4Min4m/order-service
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 80
env:
  - name: SNS_TOPIC_ARN
    value: "arn:aws:sns:us-east-1:864981715490:order-events" # Replace with actual ARN after Terraform
podAnnotations: {}
resources: {}
autoscaling:
  enabled: false
